import React from "react";
import {
  Forecast,
  ForecastHourlyContainer,
  ForecastHourlyEntryDisplay,
  Temperature,
  Time,
} from "./ForecastHourly.style";
import { WeatherHourlyArray } from "../../hooks/useWeatherFetch";
const exampleWeatherHourly = [
  {
    number: 1,
    name: "",
    startTime: "2022-01-20T08:00:00-10:00",
    endTime: "2022-01-20T09:00:00-10:00",
    isDaytime: true,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "3 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,70?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 2,
    name: "",
    startTime: "2022-01-20T09:00:00-10:00",
    endTime: "2022-01-20T10:00:00-10:00",
    isDaytime: true,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "3 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,70?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 3,
    name: "",
    startTime: "2022-01-20T10:00:00-10:00",
    endTime: "2022-01-20T11:00:00-10:00",
    isDaytime: true,
    temperature: 68,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 4,
    name: "",
    startTime: "2022-01-20T11:00:00-10:00",
    endTime: "2022-01-20T12:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 5,
    name: "",
    startTime: "2022-01-20T12:00:00-10:00",
    endTime: "2022-01-20T13:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 6,
    name: "",
    startTime: "2022-01-20T13:00:00-10:00",
    endTime: "2022-01-20T14:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 7,
    name: "",
    startTime: "2022-01-20T14:00:00-10:00",
    endTime: "2022-01-20T15:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 8,
    name: "",
    startTime: "2022-01-20T15:00:00-10:00",
    endTime: "2022-01-20T16:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 9,
    name: "",
    startTime: "2022-01-20T16:00:00-10:00",
    endTime: "2022-01-20T17:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 10,
    name: "",
    startTime: "2022-01-20T17:00:00-10:00",
    endTime: "2022-01-20T18:00:00-10:00",
    isDaytime: true,
    temperature: 69,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "ESE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers,30?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 11,
    name: "",
    startTime: "2022-01-20T18:00:00-10:00",
    endTime: "2022-01-20T19:00:00-10:00",
    isDaytime: false,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers,20?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 12,
    name: "",
    startTime: "2022-01-20T19:00:00-10:00",
    endTime: "2022-01-20T20:00:00-10:00",
    isDaytime: false,
    temperature: 60,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers,20?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 13,
    name: "",
    startTime: "2022-01-20T20:00:00-10:00",
    endTime: "2022-01-20T21:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers,20?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 14,
    name: "",
    startTime: "2022-01-20T21:00:00-10:00",
    endTime: "2022-01-20T22:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers,20?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 15,
    name: "",
    startTime: "2022-01-20T22:00:00-10:00",
    endTime: "2022-01-20T23:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers,20?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 16,
    name: "",
    startTime: "2022-01-20T23:00:00-10:00",
    endTime: "2022-01-21T00:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 17,
    name: "",
    startTime: "2022-01-21T00:00:00-10:00",
    endTime: "2022-01-21T01:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 18,
    name: "",
    startTime: "2022-01-21T01:00:00-10:00",
    endTime: "2022-01-21T02:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 19,
    name: "",
    startTime: "2022-01-21T02:00:00-10:00",
    endTime: "2022-01-21T03:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 20,
    name: "",
    startTime: "2022-01-21T03:00:00-10:00",
    endTime: "2022-01-21T04:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 21,
    name: "",
    startTime: "2022-01-21T04:00:00-10:00",
    endTime: "2022-01-21T05:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "7 mph",
    windDirection: "WNW",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 22,
    name: "",
    startTime: "2022-01-21T05:00:00-10:00",
    endTime: "2022-01-21T06:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 23,
    name: "",
    startTime: "2022-01-21T06:00:00-10:00",
    endTime: "2022-01-21T07:00:00-10:00",
    isDaytime: true,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 24,
    name: "",
    startTime: "2022-01-21T07:00:00-10:00",
    endTime: "2022-01-21T08:00:00-10:00",
    isDaytime: true,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 25,
    name: "",
    startTime: "2022-01-21T08:00:00-10:00",
    endTime: "2022-01-21T09:00:00-10:00",
    isDaytime: true,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 26,
    name: "",
    startTime: "2022-01-21T09:00:00-10:00",
    endTime: "2022-01-21T10:00:00-10:00",
    isDaytime: true,
    temperature: 63,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 27,
    name: "",
    startTime: "2022-01-21T10:00:00-10:00",
    endTime: "2022-01-21T11:00:00-10:00",
    isDaytime: true,
    temperature: 68,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 28,
    name: "",
    startTime: "2022-01-21T11:00:00-10:00",
    endTime: "2022-01-21T12:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 29,
    name: "",
    startTime: "2022-01-21T12:00:00-10:00",
    endTime: "2022-01-21T13:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 30,
    name: "",
    startTime: "2022-01-21T13:00:00-10:00",
    endTime: "2022-01-21T14:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 31,
    name: "",
    startTime: "2022-01-21T14:00:00-10:00",
    endTime: "2022-01-21T15:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 32,
    name: "",
    startTime: "2022-01-21T15:00:00-10:00",
    endTime: "2022-01-21T16:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 33,
    name: "",
    startTime: "2022-01-21T16:00:00-10:00",
    endTime: "2022-01-21T17:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 34,
    name: "",
    startTime: "2022-01-21T17:00:00-10:00",
    endTime: "2022-01-21T18:00:00-10:00",
    isDaytime: true,
    temperature: 69,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 35,
    name: "",
    startTime: "2022-01-21T18:00:00-10:00",
    endTime: "2022-01-21T19:00:00-10:00",
    isDaytime: false,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 36,
    name: "",
    startTime: "2022-01-21T19:00:00-10:00",
    endTime: "2022-01-21T20:00:00-10:00",
    isDaytime: false,
    temperature: 60,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 37,
    name: "",
    startTime: "2022-01-21T20:00:00-10:00",
    endTime: "2022-01-21T21:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 38,
    name: "",
    startTime: "2022-01-21T21:00:00-10:00",
    endTime: "2022-01-21T22:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 39,
    name: "",
    startTime: "2022-01-21T22:00:00-10:00",
    endTime: "2022-01-21T23:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 40,
    name: "",
    startTime: "2022-01-21T23:00:00-10:00",
    endTime: "2022-01-22T00:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 41,
    name: "",
    startTime: "2022-01-22T00:00:00-10:00",
    endTime: "2022-01-22T01:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 42,
    name: "",
    startTime: "2022-01-22T01:00:00-10:00",
    endTime: "2022-01-22T02:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 43,
    name: "",
    startTime: "2022-01-22T02:00:00-10:00",
    endTime: "2022-01-22T03:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 44,
    name: "",
    startTime: "2022-01-22T03:00:00-10:00",
    endTime: "2022-01-22T04:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 45,
    name: "",
    startTime: "2022-01-22T04:00:00-10:00",
    endTime: "2022-01-22T05:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 46,
    name: "",
    startTime: "2022-01-22T05:00:00-10:00",
    endTime: "2022-01-22T06:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 47,
    name: "",
    startTime: "2022-01-22T06:00:00-10:00",
    endTime: "2022-01-22T07:00:00-10:00",
    isDaytime: true,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 48,
    name: "",
    startTime: "2022-01-22T07:00:00-10:00",
    endTime: "2022-01-22T08:00:00-10:00",
    isDaytime: true,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 49,
    name: "",
    startTime: "2022-01-22T08:00:00-10:00",
    endTime: "2022-01-22T09:00:00-10:00",
    isDaytime: true,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 50,
    name: "",
    startTime: "2022-01-22T09:00:00-10:00",
    endTime: "2022-01-22T10:00:00-10:00",
    isDaytime: true,
    temperature: 63,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 51,
    name: "",
    startTime: "2022-01-22T10:00:00-10:00",
    endTime: "2022-01-22T11:00:00-10:00",
    isDaytime: true,
    temperature: 68,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 52,
    name: "",
    startTime: "2022-01-22T11:00:00-10:00",
    endTime: "2022-01-22T12:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 53,
    name: "",
    startTime: "2022-01-22T12:00:00-10:00",
    endTime: "2022-01-22T13:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 54,
    name: "",
    startTime: "2022-01-22T13:00:00-10:00",
    endTime: "2022-01-22T14:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 55,
    name: "",
    startTime: "2022-01-22T14:00:00-10:00",
    endTime: "2022-01-22T15:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 56,
    name: "",
    startTime: "2022-01-22T15:00:00-10:00",
    endTime: "2022-01-22T16:00:00-10:00",
    isDaytime: true,
    temperature: 75,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 57,
    name: "",
    startTime: "2022-01-22T16:00:00-10:00",
    endTime: "2022-01-22T17:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 58,
    name: "",
    startTime: "2022-01-22T17:00:00-10:00",
    endTime: "2022-01-22T18:00:00-10:00",
    isDaytime: true,
    temperature: 69,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 59,
    name: "",
    startTime: "2022-01-22T18:00:00-10:00",
    endTime: "2022-01-22T19:00:00-10:00",
    isDaytime: false,
    temperature: 65,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 60,
    name: "",
    startTime: "2022-01-22T19:00:00-10:00",
    endTime: "2022-01-22T20:00:00-10:00",
    isDaytime: false,
    temperature: 61,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 61,
    name: "",
    startTime: "2022-01-22T20:00:00-10:00",
    endTime: "2022-01-22T21:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 62,
    name: "",
    startTime: "2022-01-22T21:00:00-10:00",
    endTime: "2022-01-22T22:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 63,
    name: "",
    startTime: "2022-01-22T22:00:00-10:00",
    endTime: "2022-01-22T23:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 64,
    name: "",
    startTime: "2022-01-22T23:00:00-10:00",
    endTime: "2022-01-23T00:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 65,
    name: "",
    startTime: "2022-01-23T00:00:00-10:00",
    endTime: "2022-01-23T01:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 66,
    name: "",
    startTime: "2022-01-23T01:00:00-10:00",
    endTime: "2022-01-23T02:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 67,
    name: "",
    startTime: "2022-01-23T02:00:00-10:00",
    endTime: "2022-01-23T03:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 68,
    name: "",
    startTime: "2022-01-23T03:00:00-10:00",
    endTime: "2022-01-23T04:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 69,
    name: "",
    startTime: "2022-01-23T04:00:00-10:00",
    endTime: "2022-01-23T05:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "15 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 70,
    name: "",
    startTime: "2022-01-23T05:00:00-10:00",
    endTime: "2022-01-23T06:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 71,
    name: "",
    startTime: "2022-01-23T06:00:00-10:00",
    endTime: "2022-01-23T07:00:00-10:00",
    isDaytime: true,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 72,
    name: "",
    startTime: "2022-01-23T07:00:00-10:00",
    endTime: "2022-01-23T08:00:00-10:00",
    isDaytime: true,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 73,
    name: "",
    startTime: "2022-01-23T08:00:00-10:00",
    endTime: "2022-01-23T09:00:00-10:00",
    isDaytime: true,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 74,
    name: "",
    startTime: "2022-01-23T09:00:00-10:00",
    endTime: "2022-01-23T10:00:00-10:00",
    isDaytime: true,
    temperature: 63,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 75,
    name: "",
    startTime: "2022-01-23T10:00:00-10:00",
    endTime: "2022-01-23T11:00:00-10:00",
    isDaytime: true,
    temperature: 68,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 76,
    name: "",
    startTime: "2022-01-23T11:00:00-10:00",
    endTime: "2022-01-23T12:00:00-10:00",
    isDaytime: true,
    temperature: 72,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 77,
    name: "",
    startTime: "2022-01-23T12:00:00-10:00",
    endTime: "2022-01-23T13:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 78,
    name: "",
    startTime: "2022-01-23T13:00:00-10:00",
    endTime: "2022-01-23T14:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 79,
    name: "",
    startTime: "2022-01-23T14:00:00-10:00",
    endTime: "2022-01-23T15:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 80,
    name: "",
    startTime: "2022-01-23T15:00:00-10:00",
    endTime: "2022-01-23T16:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 81,
    name: "",
    startTime: "2022-01-23T16:00:00-10:00",
    endTime: "2022-01-23T17:00:00-10:00",
    isDaytime: true,
    temperature: 72,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 82,
    name: "",
    startTime: "2022-01-23T17:00:00-10:00",
    endTime: "2022-01-23T18:00:00-10:00",
    isDaytime: true,
    temperature: 68,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 83,
    name: "",
    startTime: "2022-01-23T18:00:00-10:00",
    endTime: "2022-01-23T19:00:00-10:00",
    isDaytime: false,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 84,
    name: "",
    startTime: "2022-01-23T19:00:00-10:00",
    endTime: "2022-01-23T20:00:00-10:00",
    isDaytime: false,
    temperature: 60,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 85,
    name: "",
    startTime: "2022-01-23T20:00:00-10:00",
    endTime: "2022-01-23T21:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 86,
    name: "",
    startTime: "2022-01-23T21:00:00-10:00",
    endTime: "2022-01-23T22:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 87,
    name: "",
    startTime: "2022-01-23T22:00:00-10:00",
    endTime: "2022-01-23T23:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 88,
    name: "",
    startTime: "2022-01-23T23:00:00-10:00",
    endTime: "2022-01-24T00:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 89,
    name: "",
    startTime: "2022-01-24T00:00:00-10:00",
    endTime: "2022-01-24T01:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 90,
    name: "",
    startTime: "2022-01-24T01:00:00-10:00",
    endTime: "2022-01-24T02:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 91,
    name: "",
    startTime: "2022-01-24T02:00:00-10:00",
    endTime: "2022-01-24T03:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 92,
    name: "",
    startTime: "2022-01-24T03:00:00-10:00",
    endTime: "2022-01-24T04:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 93,
    name: "",
    startTime: "2022-01-24T04:00:00-10:00",
    endTime: "2022-01-24T05:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 94,
    name: "",
    startTime: "2022-01-24T05:00:00-10:00",
    endTime: "2022-01-24T06:00:00-10:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 95,
    name: "",
    startTime: "2022-01-24T06:00:00-10:00",
    endTime: "2022-01-24T07:00:00-10:00",
    isDaytime: true,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 96,
    name: "",
    startTime: "2022-01-24T07:00:00-10:00",
    endTime: "2022-01-24T08:00:00-10:00",
    isDaytime: true,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 97,
    name: "",
    startTime: "2022-01-24T08:00:00-10:00",
    endTime: "2022-01-24T09:00:00-10:00",
    isDaytime: true,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 98,
    name: "",
    startTime: "2022-01-24T09:00:00-10:00",
    endTime: "2022-01-24T10:00:00-10:00",
    isDaytime: true,
    temperature: 62,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 99,
    name: "",
    startTime: "2022-01-24T10:00:00-10:00",
    endTime: "2022-01-24T11:00:00-10:00",
    isDaytime: true,
    temperature: 67,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "16 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 100,
    name: "",
    startTime: "2022-01-24T11:00:00-10:00",
    endTime: "2022-01-24T12:00:00-10:00",
    isDaytime: true,
    temperature: 71,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "20 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 101,
    name: "",
    startTime: "2022-01-24T12:00:00-10:00",
    endTime: "2022-01-24T13:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "20 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 102,
    name: "",
    startTime: "2022-01-24T13:00:00-10:00",
    endTime: "2022-01-24T14:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "20 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 103,
    name: "",
    startTime: "2022-01-24T14:00:00-10:00",
    endTime: "2022-01-24T15:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "20 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 104,
    name: "",
    startTime: "2022-01-24T15:00:00-10:00",
    endTime: "2022-01-24T16:00:00-10:00",
    isDaytime: true,
    temperature: 73,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "20 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 105,
    name: "",
    startTime: "2022-01-24T16:00:00-10:00",
    endTime: "2022-01-24T17:00:00-10:00",
    isDaytime: true,
    temperature: 71,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "20 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 106,
    name: "",
    startTime: "2022-01-24T17:00:00-10:00",
    endTime: "2022-01-24T18:00:00-10:00",
    isDaytime: true,
    temperature: 68,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Isolated Rain Showers",
    detailedForecast: "",
  },
  {
    number: 107,
    name: "",
    startTime: "2022-01-24T18:00:00-10:00",
    endTime: "2022-01-24T19:00:00-10:00",
    isDaytime: false,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 108,
    name: "",
    startTime: "2022-01-24T19:00:00-10:00",
    endTime: "2022-01-24T20:00:00-10:00",
    isDaytime: false,
    temperature: 60,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 109,
    name: "",
    startTime: "2022-01-24T20:00:00-10:00",
    endTime: "2022-01-24T21:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 110,
    name: "",
    startTime: "2022-01-24T21:00:00-10:00",
    endTime: "2022-01-24T22:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 111,
    name: "",
    startTime: "2022-01-24T22:00:00-10:00",
    endTime: "2022-01-24T23:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 112,
    name: "",
    startTime: "2022-01-24T23:00:00-10:00",
    endTime: "2022-01-25T00:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 113,
    name: "",
    startTime: "2022-01-25T00:00:00-10:00",
    endTime: "2022-01-25T01:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 114,
    name: "",
    startTime: "2022-01-25T01:00:00-10:00",
    endTime: "2022-01-25T02:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 115,
    name: "",
    startTime: "2022-01-25T02:00:00-10:00",
    endTime: "2022-01-25T03:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 116,
    name: "",
    startTime: "2022-01-25T03:00:00-10:00",
    endTime: "2022-01-25T04:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 117,
    name: "",
    startTime: "2022-01-25T04:00:00-10:00",
    endTime: "2022-01-25T05:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 118,
    name: "",
    startTime: "2022-01-25T05:00:00-10:00",
    endTime: "2022-01-25T06:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 119,
    name: "",
    startTime: "2022-01-25T06:00:00-10:00",
    endTime: "2022-01-25T07:00:00-10:00",
    isDaytime: true,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 120,
    name: "",
    startTime: "2022-01-25T07:00:00-10:00",
    endTime: "2022-01-25T08:00:00-10:00",
    isDaytime: true,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 121,
    name: "",
    startTime: "2022-01-25T08:00:00-10:00",
    endTime: "2022-01-25T09:00:00-10:00",
    isDaytime: true,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 122,
    name: "",
    startTime: "2022-01-25T09:00:00-10:00",
    endTime: "2022-01-25T10:00:00-10:00",
    isDaytime: true,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 123,
    name: "",
    startTime: "2022-01-25T10:00:00-10:00",
    endTime: "2022-01-25T11:00:00-10:00",
    isDaytime: true,
    temperature: 69,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 124,
    name: "",
    startTime: "2022-01-25T11:00:00-10:00",
    endTime: "2022-01-25T12:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "ENE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 125,
    name: "",
    startTime: "2022-01-25T12:00:00-10:00",
    endTime: "2022-01-25T13:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "ENE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 126,
    name: "",
    startTime: "2022-01-25T13:00:00-10:00",
    endTime: "2022-01-25T14:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "ENE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 127,
    name: "",
    startTime: "2022-01-25T14:00:00-10:00",
    endTime: "2022-01-25T15:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "ENE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 128,
    name: "",
    startTime: "2022-01-25T15:00:00-10:00",
    endTime: "2022-01-25T16:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "ENE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 129,
    name: "",
    startTime: "2022-01-25T16:00:00-10:00",
    endTime: "2022-01-25T17:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "8 mph",
    windDirection: "ENE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 130,
    name: "",
    startTime: "2022-01-25T17:00:00-10:00",
    endTime: "2022-01-25T18:00:00-10:00",
    isDaytime: true,
    temperature: 70,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 131,
    name: "",
    startTime: "2022-01-25T18:00:00-10:00",
    endTime: "2022-01-25T19:00:00-10:00",
    isDaytime: false,
    temperature: 65,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 132,
    name: "",
    startTime: "2022-01-25T19:00:00-10:00",
    endTime: "2022-01-25T20:00:00-10:00",
    isDaytime: false,
    temperature: 61,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 133,
    name: "",
    startTime: "2022-01-25T20:00:00-10:00",
    endTime: "2022-01-25T21:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 134,
    name: "",
    startTime: "2022-01-25T21:00:00-10:00",
    endTime: "2022-01-25T22:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 135,
    name: "",
    startTime: "2022-01-25T22:00:00-10:00",
    endTime: "2022-01-25T23:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "14 mph",
    windDirection: "NE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 136,
    name: "",
    startTime: "2022-01-25T23:00:00-10:00",
    endTime: "2022-01-26T00:00:00-10:00",
    isDaytime: false,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 137,
    name: "",
    startTime: "2022-01-26T00:00:00-10:00",
    endTime: "2022-01-26T01:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 138,
    name: "",
    startTime: "2022-01-26T01:00:00-10:00",
    endTime: "2022-01-26T02:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 139,
    name: "",
    startTime: "2022-01-26T02:00:00-10:00",
    endTime: "2022-01-26T03:00:00-10:00",
    isDaytime: false,
    temperature: 58,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 140,
    name: "",
    startTime: "2022-01-26T03:00:00-10:00",
    endTime: "2022-01-26T04:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 141,
    name: "",
    startTime: "2022-01-26T04:00:00-10:00",
    endTime: "2022-01-26T05:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "12 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 142,
    name: "",
    startTime: "2022-01-26T05:00:00-10:00",
    endTime: "2022-01-26T06:00:00-10:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 143,
    name: "",
    startTime: "2022-01-26T06:00:00-10:00",
    endTime: "2022-01-26T07:00:00-10:00",
    isDaytime: true,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 144,
    name: "",
    startTime: "2022-01-26T07:00:00-10:00",
    endTime: "2022-01-26T08:00:00-10:00",
    isDaytime: true,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 145,
    name: "",
    startTime: "2022-01-26T08:00:00-10:00",
    endTime: "2022-01-26T09:00:00-10:00",
    isDaytime: true,
    temperature: 59,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 146,
    name: "",
    startTime: "2022-01-26T09:00:00-10:00",
    endTime: "2022-01-26T10:00:00-10:00",
    isDaytime: true,
    temperature: 64,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 147,
    name: "",
    startTime: "2022-01-26T10:00:00-10:00",
    endTime: "2022-01-26T11:00:00-10:00",
    isDaytime: true,
    temperature: 69,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "13 mph",
    windDirection: "N",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 148,
    name: "",
    startTime: "2022-01-26T11:00:00-10:00",
    endTime: "2022-01-26T12:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 149,
    name: "",
    startTime: "2022-01-26T12:00:00-10:00",
    endTime: "2022-01-26T13:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 150,
    name: "",
    startTime: "2022-01-26T13:00:00-10:00",
    endTime: "2022-01-26T14:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 151,
    name: "",
    startTime: "2022-01-26T14:00:00-10:00",
    endTime: "2022-01-26T15:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 152,
    name: "",
    startTime: "2022-01-26T15:00:00-10:00",
    endTime: "2022-01-26T16:00:00-10:00",
    isDaytime: true,
    temperature: 76,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 153,
    name: "",
    startTime: "2022-01-26T16:00:00-10:00",
    endTime: "2022-01-26T17:00:00-10:00",
    isDaytime: true,
    temperature: 74,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "17 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 154,
    name: "",
    startTime: "2022-01-26T17:00:00-10:00",
    endTime: "2022-01-26T18:00:00-10:00",
    isDaytime: true,
    temperature: 70,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "18 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/day/rain_showers?size=small",
    shortForecast: "Scattered Rain Showers",
    detailedForecast: "",
  },
  {
    number: 155,
    name: "",
    startTime: "2022-01-26T18:00:00-10:00",
    endTime: "2022-01-26T19:00:00-10:00",
    isDaytime: false,
    temperature: 65,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "18 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
  {
    number: 156,
    name: "",
    startTime: "2022-01-26T19:00:00-10:00",
    endTime: "2022-01-26T20:00:00-10:00",
    isDaytime: false,
    temperature: 61,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "18 mph",
    windDirection: "NNE",
    icon: "https://api.weather.gov/icons/land/night/rain_showers?size=small",
    shortForecast: "Chance Rain Showers",
    detailedForecast: "",
  },
];
const convertTime = (time: string) => {
  const hour = new Date(time).getHours();
  console.log(hour);
  if (hour === 12) {
    return `${hour}pm`;
  }
  if (hour === 0) {
    return `12am`;
  }
  if (hour < 12) {
    return `${hour}am`;
  }

  return `${hour - 12}pm`;
};
interface ForecastHourlyProps {
  forecastHourlyArray: WeatherHourlyArray;
}
const ForecastHourly: React.FC<ForecastHourlyProps> = ({
  forecastHourlyArray,
}) => {
  const forecastHourlyDisplayData = forecastHourlyArray
    ? forecastHourlyArray.slice(1, 10)
    : exampleWeatherHourly.slice(1, 10);
  return (
    <ForecastHourlyContainer>
      {forecastHourlyDisplayData.map((entry) => (
        <ForecastHourlyEntryDisplay>
          <Time>{convertTime(entry.startTime)}</Time>
          <Temperature>
            {entry.temperature}
            <span>&#176;</span>
          </Temperature>
          <Forecast>{entry.shortForecast}</Forecast>
          {/* <img src={entry.icon} /> */}
        </ForecastHourlyEntryDisplay>
      ))}
    </ForecastHourlyContainer>
  );
};

export default ForecastHourly;
